spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/standard-demo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage, pageSize=pageSize
logging:
  level:
    com.woniu.dao: debug
devtools:
  restart:
    enabled: true
    additional-paths: src/main/java
